---
title: "Course Reflection"
author: "Josh Baber"
date: "7/21/2022"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Thoughts on R  

For me, R was the first programming language I ever used, so many of my ideologies about programming stem from R.  For example, whenever I am trying to do loops or make tables or something in another language, I first think to myself "How would I do this in R?".  I know that R is not a general purpose language and is slower in many ways when compared to other languages, but I rarely program for any purpose other than data science.  I will definitely be using R in the future, it is rapidly growing and is becoming the industry standard, if not already.  The support for it is amazing and I can usually find solutions to problems I have online.  The only thing about R that bugs me is the errors.  Often, the errors are not descriptive enough or fail to point out where I did something wrong.  Usually, I can still find what I did wrong with a Google search, but I still wish they were better.  Now that I have also learned a decent amount of SAS and Python, I have to say that R is still my favorite, but I would still be happy using the other two if I had to.  

## Different Practices  

This course really opened my eyes to what R is really capable of.  Before this course, I had really only used R to analyze data sets, make tables and graphs, clean data, and fit models.  I also have used it for fitting Bayesian models with STAN and JAGS.  Since this class has started, I can now use R to query APIs, automate markdown files, create Shiny apps, parallel computing, etc.  In the future, I will feel more comfortable with doing the things I have been doing in R and implementing them into new things like APIs and Shiny apps.  Also, I will probably use the `caret` package more, since it is super user friendly and most things can be done in only a few lines of code.  

## Exploring Data Science  

I will definitely be exploring tree models in the future.  I had briefly learned about them before, but I never really got a good understanding of them until taking this course.  I know there are many different ways to go about fitting them and I'm curious how they can be improved, or what good ones there are for specific situations.  I'm also curious about how they tie into the Bayesian framework of statistics.  Unsupervised learning is another thing I had never learned about, and I'm curious how it's used in the real world.  I know it plays a big role in AI, but I want to know more about how it can be applied to other areas of study.  